filter:
    excluded_paths:
        - '*.min.js'
        - '*/dist/*'
        - '*/vendor/*'
        - '*/docs/*'
        - '*/tools/*'
        - '*/tests/*'
        - '*/theme/default/bootstrap/*'
        - '*/theme/default/dist/*'
        - '*/theme/default/plugins/*'
