language: php
php:
    - 7.0
    - 7.1

addons:
    mariadb: '10.0'

before_install:
    - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension = ldap.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - mysql -e 'CREATE DATABASE yaipam_test;'
    - cp tests/config.travis.php config.php

install:
    - composer install --prefer-dist --no-interaction

script: phpunit --configuration tests/phpunit.xml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml