Addresses:
    type: entity
    table: addresses
    id:
        addressid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: AddressID
            generator:
                strategy: IDENTITY
    fields:
        address:
            type: binary
            nullable: false
            column: Address
        addressafi:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: AddressAFI
        addressstate:
            type: boolean
            nullable: false
            column: AddressState
        addressname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: AddressName
        addressfqdn:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: AddressFQDN
        addressmac:
            type: string
            nullable: false
            length: 8
            options:
                fixed: false
            column: AddressMAC
        addresstt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: AddressTT
        addressdescription:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
            column: AddressDescription
        addressprefix:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: AddressPrefix
    lifecycleCallbacks: {  }
