Prefixes:
    type: entity
    table: prefixes
    id:
        prefixid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PrefixID
            generator:
                strategy: IDENTITY
    fields:
        prefix:
            type: binary
            nullable: false
            column: Prefix
        prefixlength:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: PrefixLength
        afi:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: AFI
        rangefrom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: RangeFrom
        rangeto:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: RangeTo
        prefixdescription:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: PrefixDescription
        parentid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ParentID
        mastervrf:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: MasterVRF
        prefixstate:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: PrefixState
        prefixvlan:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: PrefixVLAN
    lifecycleCallbacks: {  }
