User:
    type: entity
    table: users
    id:
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: UserID
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: Username
        useremail:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: Useremail
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: Password
        method:
            type: integer
            nullable: false
            length: 11
            options:
                unsigned: false
            column: Method
        group:
            type: integer
            nullable: false
            length: 11
            options:
                unsigned: false
            column: Group
    lifecycleCallbacks: {  }
