Vlans:
    type: entity
    table: vlans
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        vlanid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: VlanID
        vlanname:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: VlanName
        vlandomain:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: VlanDomain
        otvdomain:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: OTVDomain
    lifecycleCallbacks: {  }
