Vrfs:
    type: entity
    table: vrfs
    id:
        vrfid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: VRFID
            generator:
                strategy: IDENTITY
    fields:
        vrfname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: VRFName
        vrfdescription:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: VRFDescription
        vrfrd:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: VRFRD
        vrfrt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: VRFRT
    lifecycleCallbacks: {  }
